### ISSUE TITLE
An error “fprintf_chk.c: No such file or directory” occurs

### ISSUE THREAD

**Issue by WuMingZhiBeii** [thunlp/MNRE#1]
您好，
When I execute the original code under Ubuntu 14.04., the error occurs:

` Segmentation fault (core dumped)`

Then, I tried to debug it with gdb, and got the following error:
```
The program received signal SIGSEGV, Segmentation fault.
___fprintf_chk (fp=0x0, flag=1, format=0x4155c6 "%d\n") at fprintf_chk.c:30
30      fprintf_chk.c: No such file or directory.
```
I have googled a lot, and find no solution, could you give me some advice to resolve that.

Thanks so much.

Kind Regards.

**Comment by Mrlyk423** [comment]
I have never met such problem. It seems that the function "fprintf" of c++ does not work in your environment. Maybe you can use "cout" instead.
